fix: do not depend on external domains in dnslink tests (#547)
Dependency on third-party domains means  that over time
CI will break, like it did in
https://github.com/ipfs/kubo/actions/runs/9214249430/job/25364989609?pr=10429#step:9:63

Error: queryCname ENODATA singularity.storage

There three domains left here are enough to cover all cases.

Ideally, CI would not depend on internet DNS, and have static fixtures
and custom localhost DNS server, but this should be good enough to stop
breaking Kubo CI etc